### ISSUE TITLE
no-used-import triggered when importing behavior

### ISSUE THREAD

**Issue by balloob** [Banno/polymer-lint#15]
I use a behavior to bind my polymer elements to my global data store. I have to import this behavior to make sure that it is available to the component, however this triggers an `no-unused-import` warning.

[Example file](https://github.com/home-assistant/home-assistant-polymer/blob/master/panels/dev-info/ha-panel-dev-info.html#L10) results in:

```
  10:1  Component 'hass-behavior' was imported but never used             no-unused-import
```

**Comment by ChadKillingsworth** [comment]
Yup - you'll need to suppress those. This can also occur if you create an element in JavaScript. The linter only looks at the html and css.

Here's an example from our codebase:

```html
<link rel="import" href="jha/dropdowns/jha-dropdown-toggle.html">
<link rel="import" href="jha/dropdowns/jha-dropdown.html">
<link rel="import" href="jha/icons/jha-icon-account.html">
<link rel="import" href="jha/icons/jha-icon-chevron-right.html">
<link rel="import" href="jha/icons/jha-icon-menu.html">
<link rel="import" href="shared-styles.html">

<!-- Imports needed for routing -->
<!-- bplint-disable no-unused-import -->
<link rel="import" href="bannoweb-account-detail.html" />
<link rel="import" href="bannoweb-dashboard.html" />
<link rel="import" href="bannoweb-recent-activity.html" />
```
