### ISSUE TITLE
New rule: no-auto-binding

### ISSUE THREAD

**Issue by jrunning** [Banno/polymer-lint#6]
Emits an error when an automatic (two-way) binding is encountered.

###### Error

```html
<template>
  {{name}}
</template>
```

###### OK

```html
<template>
  [[name]]
</template>
```

**Comment by strycore** [comment]
Can I get the reasoning behind this? I think I'm missing some info here. If automatic two way bindings are bad, what is the good alternative? I have broken working code by mindlessly applying this rule because I usually trust my linting tools not to break my projects.
It's been a few months since I've read the Polymer documentation, is there a new syntax for 2 way binding?

**Comment by ChadKillingsworth** [comment]
There has been a growing consensus in the JS community that two-way data binding should be avoided. Angular 1 definitely highlighted some of the problems with 2-way binding. Angular 2 offers both 1-way and 2-way. React is all 1-way.

Our projects use both - but we default to 1-way data binding. In the few cases where we actually want and need a 2 way binding, we suppress the linter warning. But the fast majority of uses are 1-way.

If you want to use 2-way data binding everywhere, simply don't use this particular rule.

**Comment by strycore** [comment]
Do it have to be an all-or-nothing rule? 
I can't see any usecase where a <paper-input> value attribute should have a one way binding, same for  a <paper-checkbox> checked attribute or any other element that is expected to receive user input.
For the rest, fair enough, two-way data bindings are usually not useful but a linter tool should be able to tell the difference between those cases.

**Comment by jrunning** [comment]
Two ways data-bindings are certainly useful in some situations. In particular, they're great for demos. But if the values are tied to the app's data model (as opposed to ephemeral, e.g. displaying placeholder text), then two-way data bindings introduce a second source of truth, which adds complexity, which is why "the community" is aggressively moving away from them.

In answer to your question, though, it does not have to be an all-or-nothing rule. It's already the case that no rule in polymer-lint is all-or-nothing. You can disable rules globally or within particular contexts with the `<!-- bplint-disable ... -->` directive. On the rare occasion that two-way binding is required, adding a directive not only adds an exception to the rule but also signals to others reading your code that you've (presumably) put some thought into making that exception.

In the future polymer-lint will be more configurable. It would certainly be possible to, say, let the user specify a whitelist for elements or properties that should not report an error for two-way bindings. At this point, though, polymer-lint is all of two months old and has the feature set to match.
